spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservice-product-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.139.128:3306/springcloud?serverTimezone=GMT%2B8
    username: root
    password: hive
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mxy.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:6001/eureka/,http://eureka2.com:6002/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
---
server:
  port: 8002
spring:
  profiles: prod
  application:
    name: microservice-product-prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.139.128:3306/springcloud?serverTimezone=GMT%2B8
    username: root
    password: hive
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mxy.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:6001/eureka/,http://eureka2.com:6002/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



